### ISSUE TITLE
Translate array of strings

### ISSUE THREAD

**Issue by Volodymyr-sky** [vitalets/google-translate-api#98] opened 2022-06-20 09:49 UTC
Is there a way to translate array of separate strings in one request?
I tried JSON.stringify, but in some cases I recieve text with deleted quotes, so I can't JSON.parse() to get array

**Comment by AidanWelch** [comment] 2022-07-02 11:53
Not within this API, and as far as I'm aware it is not possible in one request with the exposed endpoints of translate.google.com

**Comment by AidanWelch** [comment] 2022-07-10 23:18
Its not possible reliably that I know in 1 request, but I have it down to 1 + n requests, instead of 2n requests in my fork [here](https://github.com/AidanWelch/google-translate-api)

**Comment by vitalets** [comment] 2022-10-22 19:21
Duplicate of #101

**Closed by vitalets** 2022-10-22 19:21 UTC
