### ISSUE TITLE
Translate with multiple 'q' parameters.

### ISSUE THREAD

**Issue by EYHN** [vitalets/google-translate-api#24] opened 2019-05-27 12:48 UTC
Thank you for your great work!
The google translation API allows multiple 'q' parameters, I want to know how to calculate the token.
![image](https://user-images.githubusercontent.com/13579374/58420749-bb8a7400-80c0-11e9-93c3-1d8ebcccc1af.png)

**Comment by vitalets** [comment] 2019-05-28 09:56
Could you show example of request and response with multiple `q`?

**Comment by EYHN** [comment] 2019-05-28 11:35
Thank you for your response.
I found this request in the web translation feature of google chrome.

![image](https://user-images.githubusercontent.com/13579374/58475130-b6402e80-817f-11e9-8103-cd973695f669.png)

**Comment by vitalets** [comment] 2019-06-17 16:40
I see it uses different url:
```
https://translate.googleapi.com/...
```

and this packages uses:
```
https://translate.google.com/translate_a/single...
```

Many parameters are the same (and maybe token will fit), but it should be researched.

**Comment by coltongit** [comment] 2019-08-21 12:58
https://github.com/hua1995116/google-translate-open-api has done a similar approach to this, however, it's based on the broken code from the original repo, so it may need tweaks to be brought over here if this is what we should go for to resolve this issue.

**Comment by vitalets** [comment] 2019-09-20 11:21
I've checked current code. @EYHN correctly noted in the first message that the problem is to calculate token for request with multiple `q` params.
Currently token is [calculated](https://github.com/vitalets/google-translate-api/blob/e94af62e5656accfe9efbe3916ace5dba5d0a279/index.js#L32) for single text string. Internally it uses [obfuscated](https://github.com/vitalets/google-translate-token/blob/a171a6f57b239d4ef96ce8bb4cb495654ed67881/index.js#L14) google translate  code(

So if someone can research how to get token for list of texts - it would be great and will allow this issue to be implemented.

**Comment by tobiasmuehl** [comment] 2020-03-02 12:34
I think the TK token is created with a different algorithm. In Networks tab you can see which JS is loaded to generate the token, the obfuscated version is at https://translate.googleapis.com/element/TE_20200210_00/e/js/element/element_main.js . The URL suggests it's updated more frequently, although I can't tell if the TK generation algo is any different from the version used by https://github.com/vitalets/google-translate-token .

```js
function Ap(a, b) { for (var c = 0; c < b.length - 2; c += 3) { var d = b.charAt(c + 2); d = "a" <= d ? d.charCodeAt(0) - 87 : Number(d); d = "+" == b.charAt(c + 1) ? a >>> d : a << d; a = "+" == b.charAt(c) ? a + d & 4294967295 : a ^ d } return a }

function Bp(a, b) {
        var c = b.split("."); b = Number(c[0]) || 0; for (var d = [], e = 0, f = 0; f < a.length; f++) { var h = a.charCodeAt(f); 128 > h ? d[e++] = h : (2048 > h ? d[e++] = h >> 6 | 192 : (55296 == (h & 64512) && f + 1 < a.length && 56320 == (a.charCodeAt(f + 1) & 64512) ? (h = 65536 + ((h & 1023) << 10) + (a.charCodeAt(++f) & 1023), d[e++] = h >> 18 | 240, d[e++] = h >> 12 & 63 | 128) : d[e++] = h >> 12 | 224, d[e++] = h >> 6 & 63 | 128), d[e++] = h & 63 | 128) } a = b; for (e = 0; e < d.length; e++)a += d[e], a = Ap(a, "+-a^+6"); a = Ap(a, "+-3^+b+-f"); a ^= Number(c[1]) || 0; 0 > a && (a = (a & 2147483647) + 2147483648); c = a % 1E6; return c.toString() +
            "." + (c ^ b)
    }
```

Bp can be used to generate a TK token (a is the query, b the TKK from the HTML), just not sure what the query is for multiple `q` parameters.

**Comment by vitalets** [comment] 2021-01-25 19:02
Closing this as we moved to new Google RPC API.
See: https://github.com/vitalets/google-translate-api/pull/61

**Closed by vitalets** 2021-01-25 19:02 UTC
